name 'bkuebler-pureftpd'
version '0.0.1'

author 'Benjamin Kübler <b.kuebler@kuebler-it.de>'
license 'Apache-2.0'
project_page 'https://github.com/bkuebler/puppet-pureftpd'
source 'https://github.com/bkuebler/puppet-pureftpd.git'
summary 'A module for manage pure-ftpd with all available plugins'
description 'A module for manage pure-ftpd with all available plugins'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
